- name: install apache2
  hosts: all
  tasks:
    - name: install httpd if os is redhat
      yum:
       - name: httpd
         state: latest
    - name: install appache2 if os is debian
      apt:
       - name: install apache2
         state: latest
