- name: install apache
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: install apache on redhat
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "RedHat"

    - name: install apache on debian
      apt:
        name: apache2
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"

  