- name: my first playbook
  hosts: all
  vars:
    animal = "tiger" 
  tasks:
    - name: print animal
      debug:
        msg: "{{animal}}"
    - name: print animal2
      debug:
        msg: "{{animal}}"
    - name: print animal3
      debug:
        msg: "lion"

