- name: my first playbook
  hosts: all
  vars:
    animal: "tiger" #global variable
  vars_files:
    - ./var.txt
    - ./var2.txt
  tasks:
    - name: print animal
      debug:
        msg: "{{animal}}"
    - name: print animal2
      debug:
        msg: "{{animal2}}"
    - name: print animal3
      debug:
        msg: "{{animal}}"
      vars:
        animal: "lion"




